### ISSUE TITLE
Format without timestamps

### ISSUE THREAD

**Issue by YIRU69** [mldwr/st-transcriptifier#1]
Thank you for your sharing.
I tried your script and wanted to get an .srt file with a timestamp. However, I was only able to download a text file without a timestamp. Could you please let me know if this is an operational issue on my end?
![image](https://user-images.githubusercontent.com/48148292/230523459-07196bdd-474b-467f-8abe-bff686d2ef98.png)

**Comment by mldwr** [comment]
Hi, thank you for using my app :)
It is not an issue on your end.
I didn't include the timestamps i.e. the "srt" file, because the  goal of this script is to generate a summary.
For that I the timestamps are not necessary, which why I removed them.

However, if you want to work with a "srt" file just clone my repo and adjust the youtube_transcript_api.

**Comment by YIRU69** [comment]
Thank you for your reply. Can you teach me how to do it? I am not a software personnel. Thank you very much
